services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tp3-web
    ports:
      - '5432:5432'
    volumes:
      - tp3-web:/var/lib/postgresql/data
volumes:
  tp3-web:
